sonar.projectKey=dikevoi
sonar.projectName=DiKeVoi-Mono
sonar.projectVersion=0.1.0

# Backend
sonar.sources=backend/app
sonar.tests=backend/tests
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.python.version=3.11

sonar.exclusions=**/venv/**,**/__pycache__/**,**/node_modules/**,**/migrations/**
sonar.test.exclusions=backend/tests/**

sonar.coverage.exclusions=backend/app/firebase/**,backend/app/core/supabase.py
