#!/bin/sh
set -e

# Trap errors and display failure message
trap 'echo "❌ pre-commit checks failed!"; exit 1' ERR

# Lint in frontend
cd frontend && npm run lint

# Lint in backend
cd ../backend && source venv/bin/activate && python3 -m black . || python -m black && echo "✅ Backend formatted with Black!" &&
python3 -m flake8 app/ || python -m flake8 app/