#!/bin/sh
set -e

# Trap errors and display failure message
trap 'echo "❌ pre-push checks failed!"; exit 1' ERR

cd backend && source venv/bin/activate && pytest
sed -i 's|<source>app</source>|<source>backend/app</source>|' coverage.xml
