#!/bin/sh
set -e

# Bắt lỗi bằng EXIT thay vì ERR
finish() {
  if [ $? -ne 0 ]; then
    echo "❌ pre-push checks failed!"
  fi
}
trap finish EXIT

# Dùng dấu chấm (.) thay vì chữ source
. backend/venv/bin/activate

# Chạy test Backend
PYTHONPATH=backend pytest backend/tests \
  --override-ini=addopts= \
  --cov=backend/app \
  --cov-report=term-missing \
  --cov-report=xml:backend/coverage.xml \
  --cov-fail-under=80

# Chạy test Frontend
npm run test:coverage --prefix frontend